### STUDENT NAME : Paola Santos Perez

### STUDENT ID :1001810057

#### Question 1 (10 POINTS)

Write a function named power that takes two numbers, base and exponent, as input and returns the result of raising base to the power of exponent.

In [28]:
def power(base, exponent):
       return base**exponent


base = int(input("base:"))
exponent = int(input("exponent:"))
power(base, exponent)

base: 8
exponent: 3


512

#### Question 2 (10 POINTS)

Write a function called `calculate_average` that takes a list of numbers as a parameter and returns the average of those numbers.

In [35]:
from numpy import *
def calculate_average():
    return average(c)



c = [1, 12, 9, 7, 8]
calculate_average()

7.4

#### Question 3 (20 POINTS)

You are working on an application for a movie theater. The application needs a feature where users can specify preferences for their movie experience.

**Write a Python function named movie_preferences that:**

- Accepts an arbitrary number of keyword arguments.
- Processes these keyword arguments to set preferences for the movie-goer.
- Returns a dictionary with the preferences.

For example, if the function is called with the arguments seat="Front Row", snack="Popcorn", and drink="Soda", the function should return the dictionary:

In [87]:
def movie_preferences():
    dict = {"genre": "Fantasy",
             "seat": "last row",
             "sound design": "immersive",
             "snacks": "Nachos", 
             "drinks": "Pink Lemonade"}
    return dict

movie_preferences()

{'genre': 'Fantasy',
 'seat': 'last row',
 'sound design': 'immersive',
 'snacks': 'Nachos',
 'drinks': 'Pink Lemonade'}

In [ ]:
# How to make it input wise? 

#### Question 4 (10 POINTS)

Create two 2D NumPy arrays with shape (2, 2). Perform matrix multiplication.

In [71]:
from numpy import *

o = arange(4).reshape(2,2)
d = array([3,6,9,12]).reshape(2,2)


# below we use @ for matrix multiplication after importing everything from numpy.
o @ d

array([[ 9, 12],
       [33, 48]])

#### Question 5 (10 POINTS)

Create a 2D NumPy array with shape (3, 3). Calculate its determinant and inverse.

In [33]:
from numpy import *
y = arange(9).reshape(3,3)
y

# Hence the determinant is zero for this matrix there is no inverse

det = linalg.det(y)
print(det)


0.0


In [29]:
from numpy import *
r = array([[5, 6, 7],
          [9, 16, 67],
          [8, 7, 5]])
det = linalg.det(r)
print(det)

# because the det is not 0 it has an inverse 

linalg.inv(r)

546.0000000000006


array([[-0.71245421,  0.03479853,  0.53113553],
       [ 0.8992674 , -0.05677656, -0.4981685 ],
       [-0.11904762,  0.02380952,  0.04761905]])

#### Question 6 (20 POINTS)

Given an integer array nums, sort the array in ascending order and remove the duplicates in-place such that each unique element appears only once. Return the number of unique elements in nums and the intial sorted list.



Example 1:


Input: nums = [3,3,2,2,1,5,6,7,7,8]

Output: 7, nums = [1,2,2,3,3,5,6,7,7,8]


In [3]:
from numpy import *

b = array([8, 8, 0, 9, 6, 5, 4, 3, 2, 6])

mask= array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0], 
             dtype = bool)


In [5]:
u = b[mask]
print(u)

[8 0 9 6 5 4 3 2]


In [7]:
u.sort()
print(u)

[0 2 3 4 5 6 8 9]


In [17]:
len(u)

8

#### Question 7 (20 POINTS)

Write a Python function, **HoursMinutes_to_Seconds**, that converts given hours  and minutes into total seconds

In [144]:
from numpy import * 
def HoursMinutes_to_Seconds():
    # 1 hour = 60 minutes
   return (hour * 60 + minutes)*60





hour = int(input("Hours:"))
minutes = int(input("Minutes:"))
HoursMinutes_to_Seconds()
# standard time not military time. Thank you.




Hours: 2
Minutes: 1


7260