## Functions 

In [ ]:
# General syntax

def fucntion_name(input_arg1, input_arg2,..., input_argn):{be explicit with what the function is doing}
    code line 1
    code line 2 
    return return_variable #Optional 

# Usage 
function_name(a1, a2, ..., an)

In [2]:
# Function with no input arguments or return statements 
# No input in this fucntion. 
def helloworld():
    print("Hello World!")

In [4]:
helloworld()

Hello World!


In [ ]:
# because is a function you got to put the () at the end in oder to get it. 

In [6]:
helloworld(5)

TypeError: helloworld() takes 0 positional arguments but 1 was given

In [15]:
def square_fucntion(x):
    return x**2

In [10]:
square_fucntion(6)

36

In [12]:
square_fucntion(7.0)

49.0

In [14]:
square_fucntion('Data')

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

In [ ]:
# Because it's a mathematical function it will give an error. 

In [16]:
# calling the function somethign else 

y = square_fucntion(4)

In [18]:
y

16

## Exercise 

#### Write a fucntion and for loop to take a list of integers and return a list of the squares of all integers

In [25]:
a = [ 3, 2, 5]
u = []
for x in a: 
    u.append(square_fucntion(x))
print(u)

[9, 4, 25]


In [ ]:
# Why is it not working??

In [3]:
# How professor did it: For Loop 
lst = [10, 15, 20, 25] 
square_lst = []
for i in lst:
    square_lst.append(i**2)
print(square_lst)

[100, 225, 400, 625]


In [23]:
lst = [10, 15, 20, 25] 
square_lst = []
for i in lst:
    square_lst.append(square_fucntion(i))
print(square_lst)

[100, 225, 400, 625]


In [27]:
# Function 

def square_list(input_list): 
    square_list = []
    for i in input_list:
        square_list.append(square_fucntion(i))
    return square_list

In [29]:
square_list([5, 25])

[25, 625]

In [31]:
square_list([1, 2, 10, 9])

[1, 4, 100, 81]

In [33]:
lst = [5, 6, 7, 8]

In [35]:
square_list(lst)

[25, 36, 49, 64]

In [37]:
# defining input function 
x = float(input("Give me an integer: "))
print(type(x)) 
print(square_fucntion(x))

# Does the steps in sequence....

Give me an integer:  7


<class 'float'>
49.0


In [ ]:
# the integer I used is 7 
# class is float because we coverted to a float
# then it is squared. 

In [41]:
x = int(input("Give me an integer: "))
print(type(x)) 
print(square_fucntion(x))

Give me an integer:  5.0


ValueError: invalid literal for int() with base 10: '5.0'

In [43]:
x = int(input("Give me an integer: "))
print(type(x)) 
print(square_fucntion(x))

Give me an integer:  5


<class 'int'>
25


## Multiple Input Arguments

In [46]:
def power(base, exponent):
    return base**exponent

In [48]:
power(5,3)

125

In [50]:
power(5)
# no default value therefore there will be an error

TypeError: power() missing 1 required positional argument: 'exponent'

In [64]:
# Write your own power function: assume that exponent is a positive integer
# Is this what he wants???????
# Has to not be able to accept negative numbers. 
def power1(base, exponent):
   if exponent < 0: 
       return("Exponent can not be negative!")
   else:
       return(base**exponent)
       

In [66]:
power1( 2,4)

16

In [70]:
power1(2, -4)

'Exponent can not be negative!'

In [72]:
def quotient_remainder(number,divisor):
    return(number//divisor, number%divisor)

In [74]:
quotient_remainder(6, 72)

(0, 6)

In [76]:
quotient_remainder(6, 2)

(3, 0)

In [80]:
quotient_remainder(7,49)

(0, 7)

In [82]:
quotient_remainder(1787, 23)

(77, 16)

In [84]:
5//3

1

In [ ]:
# Above it only gives you the divisor. 

In [86]:
5%3

2

In [ ]:
# Above it only gives you the remainder. 

In [88]:
divmod(1787, 23)

(77, 16)

## Default Variables

In [97]:
def my_calculations(a, b, e= 2.71):
    return(a**b*e)

In [99]:
my_calculations(3,4)

219.51

## Nested Functions 

In [ ]:
# General Example
# figure out the # how to do it in one
#def outer_fucntion(input_args, .....):
#    def inner_function(other_input_args, ...):
#        inner function code
#        return
#        x = inner_fucntion(....)
#        return(x)

In [102]:
def divisors(x): 
    count = 0
    for i in range(1, n+1): 
        if n % i == 0: 
            count += 1
        return count

In [110]:
def stuff(base, exponents, translation): 
    #return to base**exponenet - translation ( purpose of the fucntion with comment) 
    def power(base, exponent):
        return base**exponent
        
    output = power(base, exponents) - translation
    return output
    

In [ ]:
# defined outer function and defined the inner function in the nested loop

In [112]:
stuff(5, 2, 10)

15

## Exercise:
### Write a fucntion that takes a positive integer and output a lsit of all prime numbers <+ that integer. 

In [173]:
def divisors(n): 
    count = 0
    for i in range(1, n+1): 
        if n % i == 0: 
            count += 1
        return count

In [175]:
# How professor did it: 
def is_prime(x): 
   if divisors(x) == 2: 
       return True 
   else: 
       return False

In [157]:
is_prime(10)

False

In [159]:
is_prime(5)
# Ask professor after class....

False

In [181]:
def is_prime(x):
    if divisors(x) == 2:
        return True
    else: 
        return False
        for x in range(7, n+7):
            if is_prime(x):
                is_prime.append(x)
                return primes

In [169]:
# how the professor did it: 
def list_primes(x):
    """
    Return a list of all prime nubmers less than or equal to x.
    """
    primes = [] 
    for i in range(2, x + 1):
        if is_prime(i):
            primes.append(i)
        return primes

In [183]:
list_primes(5)
# check this thing out and why is not working!!!!!!!!!

[]

## Modules and Packages

In [ ]:
# Modules and Packages are the Python's libraries. i.e. a collection of constants, functions and classes. 


## Importing a Module

In [187]:
# basic imports 
import numpy 
numpy.pi

3.141592653589793

In [189]:
# Use an "alias" 
import numpy as np

In [191]:
np.pi

3.141592653589793

In [193]:
# Importing specific elements from the package/module 

from numpy import add, pi

In [195]:
add

<ufunc 'add'>

In [197]:
pi

3.141592653589793

In [199]:
# Pull everything into the local namespace 

from numpy import *

In [201]:
%hist

# How professor did it: For Loop 
lst = [10, 15, 20, 25] 
square_lst = []
for i in lst:
    square_lst.append(i**2)
    print(square_lst)

import json
import getpass
import hashlib

def import_pandas_safely():
    try:
        return __import__('pandas')
    except ImportError:
        return False


__pandas = import_pandas_safely()


def is_data_frame(v: str):
    obj = eval(v)
    if  isinstance(obj, __pandas.core.frame.DataFrame) or isinstance(obj, __pandas.core.series.Series):
        return True


def dataframe_columns(var):
    df = eval(var)
    if isinstance(df, __pandas.core.series.Series):
        return [[df.name, str(df.dtype)]]
    return list(map(lambda col: [col, str(df[col].dtype)], df.columns))


def dtypes_str(frame):
    return str(eval(frame).dtypes)

def dataframe_hash(var):
    # Return a hash including the column names and number of rows
    df = eval(var)
    if isinstance(df, __pandas.core.series.Series):
        return hashlib.sha256(f"{var}-{df.name},{len(df

In [203]:
import numpy as np

In [207]:
np.__version__

'1.26.4'

## Numpy 

In [ ]:
# Numpy arrays 

#- define arrays 
#- indexing and slicing 
#- create arrays 
#- array calculations 
#- the array data structure 
#- advanced numpy 

In [210]:
# Introduce NumPy Arrays 

In [212]:
# Simple Array Creation 
a = array([0, 1, 2, 3])

In [214]:
a

array([0, 1, 2, 3])

In [216]:
type(a)

numpy.ndarray

In [220]:
# Numeric type of elements 
a.dtype

dtype('int32')

In [ ]:
# above you are checking the data type of the array

In [222]:
a.ddimension

AttributeError: 'numpy.ndarray' object has no attribute 'ddimension'

In [224]:
# Number of Dimenstions 
a.ndim

1

In [226]:
# Array Shape
a.shape

(4,)

In [228]:
# Bytes per element
a.itemsize

4

In [230]:
# Bytes of Memory Used
a.nbytes

16

In [236]:
# Array Operations 

a = array([1,2,3,4])
b = array([2,3,4,5])

In [238]:
a + b

array([3, 5, 7, 9])

In [240]:
a**b

array([   1,    8,   81, 1024])

In [242]:
# math fucntions 

# create an array from 0 to 10 

x = arange(11)

In [244]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# the a at the front of the arange makes it into an array

In [246]:
c = (2*pi)/10

In [248]:
c

0.6283185307179586

In [250]:
c * x 

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [ ]:
# in place operations ( Professor is gonna check this ) 
x *= c 

In [252]:
# apply functions to array 

y = sin(x) 

In [254]:
y

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [256]:
%hist

# How professor did it: For Loop 
lst = [10, 15, 20, 25] 
square_lst = []
for i in lst:
    square_lst.append(i**2)
    print(square_lst)

import json
import getpass
import hashlib

def import_pandas_safely():
    try:
        return __import__('pandas')
    except ImportError:
        return False


__pandas = import_pandas_safely()


def is_data_frame(v: str):
    obj = eval(v)
    if  isinstance(obj, __pandas.core.frame.DataFrame) or isinstance(obj, __pandas.core.series.Series):
        return True


def dataframe_columns(var):
    df = eval(var)
    if isinstance(df, __pandas.core.series.Series):
        return [[df.name, str(df.dtype)]]
    return list(map(lambda col: [col, str(df[col].dtype)], df.columns))


def dtypes_str(frame):
    return str(eval(frame).dtypes)

def dataframe_hash(var):
    # Return a hash including the column names and number of rows
    df = eval(var)
    if isinstance(df, __pandas.core.series.Series):
        return hashlib.sha256(f"{var}-{df.name},{len(df